import type { TalentDefinition } from '../types/progression'

export const TALENT_IDS = {
  battleHardenedOne: 'battle-hardened-1',
  twinArsenal: 'twin-arsenal',
  strikerPattern: 'striker-pattern',
  shieldcraft: 'shieldcraft',
  thirdGrip: 'third-grip',
  healingArts: 'healing-arts',
  fourthGrip: 'fourth-grip',
  bloodwellDoctrine: 'bloodwell-doctrine',
  executionerDoctrine: 'executioner-doctrine',
  towerDiscipline: 'tower-discipline',
  volatileTemper: 'volatile-temper',
  efficientTools: 'efficient-tools',
  faceMastery: 'face-mastery',
  autoCombat: 'auto-roll',
  quickDraw: 'quick-draw',
  battleHardenedTwo: 'battle-hardened-2',
  fieldStudies: 'field-studies',
  soulHarvest: 'soul-harvest',
  fatecraft: 'fatecraft',
  fatesFavor: 'fates-favor',
  wovenPair: 'woven-pair',
  trinityKnot: 'trinity-knot',
  occultProspecting: 'occult-prospecting',
  resonantEtching: 'resonant-etching',
  deepDelver: 'deep-delver',
  forgeOvercharge: 'forge-overcharge',
} as const

export const TALENTS: TalentDefinition[] = [
  {
    id: TALENT_IDS.resonantEtching,
    name: 'Resonant Etching',
    description: 'Each rank adds a 12% chance for a Workshop hit on an Imprint to gain +1 extra Imprint Power.',
    iconKey: 'resonant-etching',
    prerequisiteIds: [TALENT_IDS.faceMastery],
    ranks: [
      { cost: 28, effects: [{ type: 'imprint_forge_bonus_chance', chance: 0.12 }] },
      { cost: 52, effects: [{ type: 'imprint_forge_bonus_chance', chance: 0.12 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.battleHardenedOne,
    name: 'Inner Spark',
    description: 'Increase Max HP by 1 per rank. The first rank opens the connected progression web.',
    iconKey: 'battle-heart',
    prerequisiteIds: [],
    ranks: [
      { cost: 4, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 7, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 11, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 16, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 24, effects: [{ type: 'max_hp', amount: 1 }] },
    ],
    track: 'core',
  },
  {
    id: TALENT_IDS.twinArsenal,
    name: 'Second Grip',
    description: 'Gain a second dice slot. Which die fills it is your choice.',
    iconKey: 'twin-dice',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [{ cost: 16, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.strikerPattern,
    name: 'Striker Pattern',
    description: 'Receive the permanent Striker Die without automatically equipping it.',
    iconKey: 'striker-pattern',
    prerequisiteIds: [TALENT_IDS.twinArsenal, TALENT_IDS.volatileTemper],
    prerequisiteCount: 1,
    ranks: [{ cost: 16, effects: [{ type: 'grant_die', dieId: 'attack-die-2' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.shieldcraft,
    name: 'Shieldcraft',
    description: 'Receive the permanent Iron Guard Die.',
    iconKey: 'shieldcraft',
    prerequisiteIds: [TALENT_IDS.twinArsenal, TALENT_IDS.strikerPattern],
    ranks: [{ cost: 42, effects: [{ type: 'grant_die', dieId: 'shield-die-1' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.thirdGrip,
    name: 'Third Grip',
    description: 'Gain a third dice slot after combining defense with deeper reserves.',
    iconKey: 'twin-dice',
    prerequisiteIds: [TALENT_IDS.shieldcraft, TALENT_IDS.battleHardenedTwo],
    ranks: [{ cost: 58, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.healingArts,
    name: 'Healing Arts',
    description: 'Receive the permanent Vitality Die.',
    iconKey: 'healing-arts',
    prerequisiteIds: [TALENT_IDS.thirdGrip],
    ranks: [{ cost: 78, effects: [{ type: 'grant_die', dieId: 'heal-die-1' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.fourthGrip,
    name: 'Fourth Grip',
    description: 'Gain a fourth dice slot. Its XP cost is tuned as an early Dungeon 2 power spike.',
    iconKey: 'twin-dice',
    prerequisiteIds: [TALENT_IDS.healingArts, TALENT_IDS.executionerDoctrine, TALENT_IDS.bloodwellDoctrine],
    prerequisiteCount: 2,
    ranks: [{ cost: 2500, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.bloodwellDoctrine,
    name: 'Bloodwell Doctrine',
    description: 'Receive a Heal Signature Die with two Drain faces. Deeper Dungeons fund it faster.',
    iconKey: 'bloodwell-die',
    prerequisiteIds: [TALENT_IDS.healingArts],
    ranks: [{ cost: 1250, effects: [{ type: 'grant_die', dieId: 'heal-die-bloodwell' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.executionerDoctrine,
    name: 'Executioner Doctrine',
    description: 'Receive an Attack Signature Die with two Execute faces.',
    iconKey: 'executioner-die',
    prerequisiteIds: [TALENT_IDS.thirdGrip],
    ranks: [{ cost: 135, effects: [{ type: 'grant_die', dieId: 'attack-die-executioner' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.towerDiscipline,
    name: 'Tower Discipline',
    description: 'Receive a Shield Signature Die with two Fortify faces.',
    iconKey: 'tower-die',
    prerequisiteIds: [TALENT_IDS.thirdGrip, TALENT_IDS.battleHardenedTwo],
    ranks: [{ cost: 110, effects: [{ type: 'grant_die', dieId: 'shield-die-tower' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.volatileTemper,
    name: 'Loaded Alloy',
    description: 'Improve the permanent Workshop Die that powers every Forge.',
    iconKey: 'volatile-temper',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 8, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 1, 2, 2] }] },
      { cost: 16, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 2, 2, 2] }] },
      { cost: 28, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 2, 2, 3] }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.efficientTools,
    name: 'Efficient Tools',
    description: 'Reduce every Workshop Soul cost by 10% per rank.',
    iconKey: 'workshop-efficiency',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 10, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.9 }] },
      { cost: 22, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.9 }] },
      { cost: 40, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.9 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.faceMastery,
    name: 'Face Mastery',
    description: 'Gain one optional target-face reroll per rank during every Workshop Forge.',
    iconKey: 'face-mastery',
    prerequisiteIds: [TALENT_IDS.volatileTemper, TALENT_IDS.efficientTools],
    prerequisiteCount: 1,
    ranks: [
      { cost: 14, effects: [{ type: 'workshop_target_rerolls', amount: 1 }] },
      { cost: 30, effects: [{ type: 'workshop_target_rerolls', amount: 1 }] },
      { cost: 55, effects: [{ type: 'workshop_target_rerolls', amount: 1 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.autoCombat,
    name: 'Auto Combat',
    description: 'Automatically roll, resolve and continue while the game is open.',
    iconKey: 'auto-roll',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [{ cost: 6, effects: [{ type: 'unlock_auto_combat' }] }],
    track: 'descent',
  },
  {
    id: TALENT_IDS.forgeOvercharge,
    name: 'Forge Overcharge',
    description: 'Each rank adds a chance for a normal Workshop hit to gain +1 extra power.',
    iconKey: 'forge-overcharge',
    prerequisiteIds: [TALENT_IDS.faceMastery],
    ranks: [
      { cost: 20, effects: [{ type: 'workshop_forge_bonus_chance', chance: 0.08 }] },
      { cost: 42, effects: [{ type: 'workshop_forge_bonus_chance', chance: 0.08 }] },
      { cost: 78, effects: [{ type: 'workshop_forge_bonus_chance', chance: 0.09 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.deepDelver,
    name: 'Deep Delver',
    description: 'Increase the higher-dungeon bonus to Fate Token and Imprint drop chances.',
    iconKey: 'deep-delver',
    prerequisiteIds: [TALENT_IDS.fatecraft],
    ranks: [
      { cost: 34, effects: [{ type: 'dungeon_loot_multiplier', multiplier: 1.15 }] },
      { cost: 68, effects: [{ type: 'dungeon_loot_multiplier', multiplier: 1.15 }] },
    ],
    track: 'descent',
  },
  {
    id: TALENT_IDS.quickDraw,
    name: 'Quick Draw',
    description: 'Dice roll and score animations play 15% faster per rank.',
    iconKey: 'quick-draw',
    prerequisiteIds: [TALENT_IDS.autoCombat],
    ranks: [
      { cost: 10, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
      { cost: 18, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
      { cost: 28, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
    ],
    track: 'descent',
  },
  {
    id: TALENT_IDS.battleHardenedTwo,
    name: 'Deep Reserves',
    description: 'Increase Max HP by 2 per rank for longer descents.',
    iconKey: 'battle-heart-advanced',
    prerequisiteIds: [TALENT_IDS.fieldStudies],
    ranks: [
      { cost: 18, effects: [{ type: 'max_hp', amount: 2 }] },
      { cost: 28, effects: [{ type: 'max_hp', amount: 2 }] },
      { cost: 42, effects: [{ type: 'max_hp', amount: 2 }] },
    ],
    track: 'descent',
  },
  {
    id: TALENT_IDS.fieldStudies,
    name: 'Field Studies',
    description: 'Gain +1 XP from every defeated enemy per rank.',
    iconKey: 'xp-efficiency',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 5, effects: [{ type: 'xp_per_kill', amount: 1 }] },
      { cost: 14, effects: [{ type: 'xp_per_kill', amount: 1 }] },
      { cost: 30, effects: [{ type: 'xp_per_kill', amount: 1 }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.soulHarvest,
    name: 'Soul Die Mastery',
    description: 'Improve one permanent face on the Soul Die per rank.',
    iconKey: 'soul-efficiency',
    prerequisiteIds: [TALENT_IDS.fieldStudies],
    ranks: [
      { cost: 5, effects: [{ type: 'soul_die_faces', values: [1, 1, 2, 2, 2, 2] }] },
      { cost: 14, effects: [{ type: 'soul_die_faces', values: [1, 1, 2, 2, 2, 3] }] },
      { cost: 30, effects: [{ type: 'soul_die_faces', values: [1, 2, 2, 2, 2, 3] }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.fatecraft,
    name: 'Fatecraft',
    description: 'Enemies can now drop Fate Tokens. Spend 5 to draw one permanent Charm.',
    iconKey: 'fate-seal',
    prerequisiteIds: [TALENT_IDS.fieldStudies, TALENT_IDS.soulHarvest],
    prerequisiteCount: 1,
    ranks: [{
      cost: 30,
      effects: [
        { type: 'unlock_charms' },
        { type: 'charm_slots', amount: 1 },
      ],
    }],
    track: 'fate',
  },
  {
    id: TALENT_IDS.fatesFavor,
    name: "Fate's Favor",
    description: 'Add visible rarity protection to Fate Draws. No protection exists before rank 1.',
    iconKey: 'fate-favor',
    prerequisiteIds: [TALENT_IDS.fatecraft],
    ranks: [
      { cost: 18, effects: [{ type: 'charm_rarity_protection', epicThreshold: 8 }] },
      { cost: 36, effects: [{ type: 'charm_rarity_protection', epicThreshold: 6 }] },
      { cost: 64, effects: [{ type: 'charm_rarity_protection', epicThreshold: 6, legendaryThreshold: 15 }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.occultProspecting,
    name: 'Occult Prospecting',
    description: 'Increase both Fate Token and Imprint drop chances by 15% per rank.',
    iconKey: 'occult-prospecting',
    prerequisiteIds: [TALENT_IDS.fatecraft],
    ranks: [
      { cost: 22, effects: [{ type: 'fate_drop_multiplier', multiplier: 1.15 }, { type: 'imprint_drop_multiplier', multiplier: 1.15 }] },
      { cost: 44, effects: [{ type: 'fate_drop_multiplier', multiplier: 1.15 }, { type: 'imprint_drop_multiplier', multiplier: 1.15 }] },
      { cost: 76, effects: [{ type: 'fate_drop_multiplier', multiplier: 1.15 }, { type: 'imprint_drop_multiplier', multiplier: 1.15 }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.wovenPair,
    name: 'Woven Pair',
    description: 'Open a second Charm slot for paired Fatecraft builds.',
    iconKey: 'charm-pair',
    prerequisiteIds: [TALENT_IDS.fatecraft],
    ranks: [{ cost: 45, effects: [{ type: 'charm_slots', amount: 1 }] }],
    track: 'fate',
  },
  {
    id: TALENT_IDS.trinityKnot,
    name: 'Trinity Knot',
    description: 'Open a third and final Charm slot.',
    iconKey: 'charm-trinity',
    prerequisiteIds: [TALENT_IDS.wovenPair],
    ranks: [{ cost: 1400, effects: [{ type: 'charm_slots', amount: 1 }] }],
    track: 'fate',
  },
]

export const TALENTS_BY_ID = Object.fromEntries(
  TALENTS.map((talent) => [talent.id, talent]),
) as Record<string, TalentDefinition>
