import type { TalentDefinition } from '../types/progression'

export const TALENT_IDS = {
  battleHardenedOne: 'battle-hardened-1',
  twinArsenal: 'twin-arsenal',
  strikerPattern: 'striker-pattern',
  shieldcraft: 'shieldcraft',
  thirdGrip: 'third-grip',
  healingArts: 'healing-arts',
  fourthGrip: 'fourth-grip',
  executionerDoctrine: 'executioner-doctrine',
  towerDiscipline: 'tower-discipline',
  volatileTemper: 'volatile-temper',
  efficientTools: 'efficient-tools',
  faceMastery: 'face-mastery',
  autoCombat: 'auto-roll',
  quickDraw: 'quick-draw',
  battleHardenedTwo: 'battle-hardened-2',
  secondDescent: 'second-descent',
  fieldStudies: 'field-studies',
  soulHarvest: 'soul-harvest',
  fatecraft: 'fatecraft',
} as const

export const TALENTS: TalentDefinition[] = [
  {
    id: TALENT_IDS.battleHardenedOne,
    name: 'Inner Spark',
    description: 'Increase Max HP by 1 per rank. The first rank reveals all four paths.',
    iconKey: 'battle-heart',
    prerequisiteIds: [],
    ranks: [
      { cost: 4, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 7, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 11, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 16, effects: [{ type: 'max_hp', amount: 1 }] },
      { cost: 24, effects: [{ type: 'max_hp', amount: 1 }] },
    ],
    track: 'core',
  },
  {
    id: TALENT_IDS.twinArsenal,
    name: 'Second Grip',
    description: 'Gain a second dice slot. Which die fills it is your choice.',
    iconKey: 'twin-dice',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [{ cost: 16, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.strikerPattern,
    name: 'Striker Pattern',
    description: 'Receive the permanent Striker Die without automatically equipping it.',
    iconKey: 'striker-pattern',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [{ cost: 16, effects: [{ type: 'grant_die', dieId: 'attack-die-2' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.shieldcraft,
    name: 'Shieldcraft',
    description: 'Receive the permanent Iron Guard Die.',
    iconKey: 'shieldcraft',
    prerequisiteIds: [TALENT_IDS.twinArsenal, TALENT_IDS.strikerPattern],
    prerequisiteCount: 1,
    ranks: [{ cost: 42, effects: [{ type: 'grant_die', dieId: 'shield-die-1' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.thirdGrip,
    name: 'Third Grip',
    description: 'Gain a third dice slot after investing in two Arsenal foundations.',
    iconKey: 'third-grip',
    prerequisiteIds: [
      TALENT_IDS.twinArsenal,
      TALENT_IDS.strikerPattern,
      TALENT_IDS.shieldcraft,
    ],
    prerequisiteCount: 2,
    ranks: [{ cost: 58, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.healingArts,
    name: 'Healing Arts',
    description: 'Receive the permanent Vitality Die.',
    iconKey: 'healing-arts',
    prerequisiteIds: [
      TALENT_IDS.shieldcraft,
      TALENT_IDS.thirdGrip,
    ],
    prerequisiteCount: 2,
    ranks: [{ cost: 78, effects: [{ type: 'grant_die', dieId: 'heal-die-1' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.fourthGrip,
    name: 'Fourth Grip',
    description: 'Gain a fourth dice slot.',
    iconKey: 'fourth-grip',
    prerequisiteIds: [TALENT_IDS.healingArts],
    ranks: [{ cost: 105, effects: [{ type: 'dice_slots', amount: 1 }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.executionerDoctrine,
    name: 'Executioner Doctrine',
    description: 'Receive an Attack Signature Die with two Execute faces.',
    iconKey: 'executioner-die',
    prerequisiteIds: [TALENT_IDS.fourthGrip],
    ranks: [{ cost: 135, effects: [{ type: 'grant_die', dieId: 'attack-die-executioner' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.towerDiscipline,
    name: 'Tower Discipline',
    description: 'Receive a Shield Signature Die with two Fortify faces.',
    iconKey: 'tower-die',
    prerequisiteIds: [TALENT_IDS.shieldcraft, TALENT_IDS.thirdGrip],
    prerequisiteCount: 2,
    ranks: [{ cost: 110, effects: [{ type: 'grant_die', dieId: 'shield-die-tower' }] }],
    track: 'arsenal',
  },
  {
    id: TALENT_IDS.volatileTemper,
    name: 'Loaded Alloy',
    description: 'Improve the permanent Workshop Die that powers every Forge.',
    iconKey: 'volatile-temper',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 8, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 1, 2, 2] }] },
      { cost: 16, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 2, 2, 2] }] },
      { cost: 28, effects: [{ type: 'workshop_die_faces', values: [1, 1, 1, 2, 2, 3] }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.efficientTools,
    name: 'Efficient Tools',
    description: 'Reduce every Workshop Soul cost by 20% per rank.',
    iconKey: 'workshop-efficiency',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 10, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.8 }] },
      { cost: 22, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.8 }] },
      { cost: 40, effects: [{ type: 'workshop_cost_multiplier', multiplier: 0.8 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.faceMastery,
    name: 'Face Mastery',
    description: 'Increase the maximum value of every normal die face by 1 per rank.',
    iconKey: 'face-mastery',
    prerequisiteIds: [TALENT_IDS.volatileTemper, TALENT_IDS.efficientTools],
    prerequisiteCount: 1,
    ranks: [
      { cost: 30, effects: [{ type: 'face_cap', amount: 1 }] },
      { cost: 50, effects: [{ type: 'face_cap', amount: 1 }] },
      { cost: 80, effects: [{ type: 'face_cap', amount: 1 }] },
    ],
    track: 'workshop',
  },
  {
    id: TALENT_IDS.autoCombat,
    name: 'Auto Combat',
    description: 'Automatically roll, resolve and continue while the game is open.',
    iconKey: 'auto-roll',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [{ cost: 6, effects: [{ type: 'unlock_auto_combat' }] }],
    track: 'descent',
  },
  {
    id: TALENT_IDS.quickDraw,
    name: 'Quick Draw',
    description: 'Dice roll and score animations play 15% faster per rank.',
    iconKey: 'quick-draw',
    prerequisiteIds: [TALENT_IDS.autoCombat],
    ranks: [
      { cost: 10, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
      { cost: 18, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
      { cost: 28, effects: [{ type: 'roll_speed', multiplier: 1.15 }] },
    ],
    track: 'descent',
  },
  {
    id: TALENT_IDS.battleHardenedTwo,
    name: 'Deep Reserves',
    description: 'Increase Max HP by 2 per rank for longer descents.',
    iconKey: 'battle-heart-advanced',
    prerequisiteIds: [TALENT_IDS.autoCombat, TALENT_IDS.quickDraw],
    prerequisiteCount: 1,
    ranks: [
      { cost: 18, effects: [{ type: 'max_hp', amount: 2 }] },
      { cost: 28, effects: [{ type: 'max_hp', amount: 2 }] },
      { cost: 42, effects: [{ type: 'max_hp', amount: 2 }] },
    ],
    track: 'descent',
  },
  {
    id: TALENT_IDS.secondDescent,
    name: 'Second Descent',
    description: 'Open the path to The Iron Descent through any two connected disciplines.',
    iconKey: 'second-descent',
    prerequisiteIds: [
      TALENT_IDS.autoCombat,
      TALENT_IDS.quickDraw,
      TALENT_IDS.battleHardenedTwo,
    ],
    prerequisiteCount: 2,
    requirements: [{
      type: 'dungeon_clear',
      dungeonId: 'prototype-depths',
      count: 1,
    }],
    ranks: [{ cost: 75, effects: [{ type: 'unlock_dungeon', dungeonId: 'iron-depths' }] }],
    track: 'descent',
  },
  {
    id: TALENT_IDS.fieldStudies,
    name: 'Field Studies',
    description: 'Gain +1 XP from every defeated enemy per rank.',
    iconKey: 'xp-efficiency',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 5, effects: [{ type: 'xp_per_kill', amount: 1 }] },
      { cost: 14, effects: [{ type: 'xp_per_kill', amount: 1 }] },
      { cost: 30, effects: [{ type: 'xp_per_kill', amount: 1 }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.soulHarvest,
    name: 'Soul Harvest',
    description: 'Gain +1 Soul from every defeated enemy per rank.',
    iconKey: 'soul-efficiency',
    prerequisiteIds: [TALENT_IDS.battleHardenedOne],
    ranks: [
      { cost: 5, effects: [{ type: 'souls_per_kill', amount: 1 }] },
      { cost: 14, effects: [{ type: 'souls_per_kill', amount: 1 }] },
      { cost: 30, effects: [{ type: 'souls_per_kill', amount: 1 }] },
    ],
    track: 'fate',
  },
  {
    id: TALENT_IDS.fatecraft,
    name: 'Fatecraft',
    description: 'Future path: Charms and their dedicated currency.',
    iconKey: 'fate-seal',
    prerequisiteIds: [TALENT_IDS.fieldStudies, TALENT_IDS.soulHarvest],
    prerequisiteCount: 2,
    requirements: [{
      type: 'dungeon_clear',
      dungeonId: 'prototype-depths',
      count: 1,
    }],
    availability: 'future',
    ranks: [{ cost: 75, effects: [{ type: 'unlock_charms' }] }],
    track: 'fate',
  },
]

export const TALENTS_BY_ID = Object.fromEntries(
  TALENTS.map((talent) => [talent.id, talent]),
) as Record<string, TalentDefinition>
